# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "fetch certificate"
  lane :featch_certificates do
    bundle_identifiers = [BUNDLE_ID, EXTENSION_BUNDLE_ID]
    match(type: "appstore", app_identifier: bundle_identifiers, readonly: true)
  end
  
  desc "update certificate"
  lane :update_certificates do
    bundle_identifiers = [BUNDLE_ID, EXTENSION_BUNDLE_ID]
    match(type: "appstore", app_identifier: bundle_identifiers, force: true)
  end

  desc "upload staging to testflight"
  lane :staging do
    build_app(scheme: "RecipeApp", configuration: "Staging")
    upload_to_testflight
  end

  desc "Upload dev to testflight"
  lane :dev do
    build_app(scheme: "RecipeApp", configuration: "Debug")
    # upload_to_testflight
  end

  desc "Release to testflight"
  lane :release do
    build_app(scheme: "RecipeApp", configuration: "Release")
    upload_to_testflight
  end
end
