# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  #   increment_build_number(xcodeproj: "ReactNativeStarterKit.xcodeproj")
  #   build_app(workspace: "ReactNativeStarterKit.xcworkspace", scheme: "ReactNativeStarterKit")
  #   # upload_to_testflight
  # end

  desc "upload staging to testflight"
  lane :staging do
    build_app(scheme: "ReactNativeStarterKit", configuration: "Staging")
    upload_to_testflight
  end

  desc "Upload dev to testflight"
  lane :dev do
    match(git_basic_authorization: 'dG1kX21vYmlsZV90ZWFtOkRZaEM2YkZlNVRZa3pxVmhiTFFV')
    build_app(configuration: "Debug", workspace: "ReactNativeStarterKit.xcworkspace", scheme: "ReactNativeStarterKit")
    upload_to_testflight
  end

  desc "Release to testflight"
  lane :release do
    build_app(scheme: "ReactNativeStarterKit", configuration: "Release")
    upload_to_testflight
  end
end
